#!/bin/bash
dir="user/class/batch"
if[! -d "$dir"];then 
mkdir -p "$dir"
echo "Directory $dir created"
else 
echo "Directory $dir already exists"
fi
read -p"Enter the filename to create" filename
touch "$dir/filename"
echo "file $filename created at $dir"


or


dir="user/class/batch"
mkdir -p "$dir"
touch "$dir/filename"
echo "file $filename created at $dir"